flatpak: Don't specify branch
Apparently, this breaks the Flatpak CI yaml assumptions and makes the
"build-bundle" step there break with the following error:

> error: Refspec 'app/org.gnome.Geary.Devel/x86_64/test' not found